apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  MYSQL_USER: shopsphere_app
  MYSQL_PASSWORD: {{ .Values.backend.mysql.password | quote }}