apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: shopsphere

type: Opaque

stringData:
  MYSQL_USER: shopsphere_app
  MYSQL_PASSWORD: ShopSphereApp@2026

  # stringData use karne par Kubernetes internally Secret data ko encode/store karta hai. Base64 encryption nahi hota; production mein proper secret-management/KMS approach use karna better hai.