apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shopsphere

spec:
  selector:
    app: backend

  ports:
    - port: 8081
      targetPort: 8081

  type: ClusterIP


  # ==========================================
  # Backend check
  # ==========================================
  # kubectl get pods -n shopsphere
  # kubectl get svc -n shopsphere


# ==========================================
# Backend Service ke endpoints check
# ==========================================
# kubectl get endpoints backend -n shopsphere



# ==========================================
# Frontend Pod se Backend test
# ==========================================
# kubectl get pods -n shopsphere
# kubectl exec -it <frontend-pod-name> -n shopsphere -- sh   (Container ke andar)
# wget -qO- http://backend:8081 # Agar health endpoint configured nahi hai, to simply connection test:




# ==========================================
# Frontend → Backend connectivity test
# ==========================================

# kubectl get pods -n shopsphere
# kubectl get svc -n shopsphere
# kubectl get endpoints backend -n shopsphere