apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: shopsphere

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: anitaraut/shopsphere-frontend:v1

          ports:
            - containerPort: 3000

          imagePullPolicy: Always # Always pull the image to ensure the latest version is used

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5