apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: shopsphere
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: shopsphere
  MYSQL_USER: shopsphere_app
  MYSQL_PASSWORD: ShopSphereApp@2026