# ======================================================
# BACKEND CONFIGURATION
# ======================================================

backend:
  replicaCount: 2

  image:
    repository: anitaraut/shopsphere-backend
    tag: "v1"
    pullPolicy: Always

  port: 8081

  mysql:
    username: shopsphere_app
    password: "ShopSphereApp@2026"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# ======================================================
# FRONTEND CONFIGURATION
# ======================================================
      
frontend:
  replicaCount: 2

  image:
    repository: anitaraut/shopsphere-frontend
    tag: "v1"
    pullPolicy: Always

  containerPort: 3000
  healthPath: /health

  service:
    type: ClusterIP
    port: 3000



  