backend:
  replicaCount: 2

  image:
    repository: anitaraut/shopsphere-backend
    tag: "v1"
    pullPolicy: Always

  port: 8081

  mysql:
    password: "ShopSphereApp@2026"

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "500m"
      memory: "512Mi"