spring.application.name=shopsphere-backend

server.port=8081

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


spring.datasource.url=jdbc:mysql://localhost:3306/shopsphere
spring.datasource.username=shopsphere_app
spring.datasource.password=ShopSphereApp@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect